"""Initial Migration

Revision ID: ab7d403b7a8e
Revises: 
Create Date: 2024-11-24 16:57:56.212983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7d403b7a8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('idx_cases_description')
        batch_op.drop_index('idx_cases_title')

    with op.batch_alter_table('chat_histories', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('idx_chat_histories_session_id')
        batch_op.drop_constraint('chat_histories_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_sessions_user_id')

    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('idx_methods_description')
        batch_op.drop_index('idx_methods_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.create_index('idx_methods_title', ['title'], unique=False)
        batch_op.create_index('idx_methods_description', ['description'], unique=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_chat_sessions_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('chat_histories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_histories_session_id_fkey', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_chat_histories_session_id', ['session_id'], unique=False)
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('idx_cases_title', ['title'], unique=False)
        batch_op.create_index('idx_cases_description', ['description'], unique=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
